# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LdfVfiServiceStub:
    """Service exposed by the Python daemon to orchestrate frame interpolation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/viduce.vfi.LdfVfiService/CreateSession',
                request_serializer=service__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=service__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.InterpolateChunk = channel.unary_unary(
                '/viduce.vfi.LdfVfiService/InterpolateChunk',
                request_serializer=service__pb2.InterpolateChunkRequest.SerializeToString,
                response_deserializer=service__pb2.InterpolateChunkResponse.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/viduce.vfi.LdfVfiService/DestroySession',
                request_serializer=service__pb2.DestroySessionRequest.SerializeToString,
                response_deserializer=service__pb2.DestroySessionResponse.FromString,
                _registered_method=True)


class LdfVfiServiceServicer:
    """Service exposed by the Python daemon to orchestrate frame interpolation.
    """

    def CreateSession(self, request, context):
        """Initialize an interpolation session and negotiate shared memory mapping.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InterpolateChunk(self, request, context):
        """Execute interpolation on a chunk staged in the input shared memory buffer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """Finalize an active session and release all associated GPU / host resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LdfVfiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=service__pb2.CreateSessionRequest.FromString,
                    response_serializer=service__pb2.CreateSessionResponse.SerializeToString,
            ),
            'InterpolateChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.InterpolateChunk,
                    request_deserializer=service__pb2.InterpolateChunkRequest.FromString,
                    response_serializer=service__pb2.InterpolateChunkResponse.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=service__pb2.DestroySessionRequest.FromString,
                    response_serializer=service__pb2.DestroySessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'viduce.vfi.LdfVfiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('viduce.vfi.LdfVfiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LdfVfiService:
    """Service exposed by the Python daemon to orchestrate frame interpolation.
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/viduce.vfi.LdfVfiService/CreateSession',
            service__pb2.CreateSessionRequest.SerializeToString,
            service__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InterpolateChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/viduce.vfi.LdfVfiService/InterpolateChunk',
            service__pb2.InterpolateChunkRequest.SerializeToString,
            service__pb2.InterpolateChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/viduce.vfi.LdfVfiService/DestroySession',
            service__pb2.DestroySessionRequest.SerializeToString,
            service__pb2.DestroySessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
